plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'net.darkhax.curseforgegradle'
    id "com.modrinth.minotaur"
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

configurations {
    shadowIn
    implementation.extendsFrom shadowIn
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

shadowJar {
    archiveClassifier.set("dev-shadow")
    configurations = [project.configurations.shadowIn]

    relocate 'org.json', "${project.group}.${mod_id}.shadow.org.json"
    relocate 'org.slf4j', "${project.group}.${mod_id}.shadow.org.slf4j"
    relocate 'certificates', "${project.group}.${mod_id}.shadow.certificates"
    relocate 'com.fasterxml', "${project.group}.${mod_id}.shadow.com.fasterxml"
    relocate 'org.jsoup', "${project.group}.${mod_id}.shadow.org.jsoup"
    relocate 'mozilla', "${project.group}.${mod_id}.shadow.mozilla"
    relocate 'net.iharder', "${project.group}.${mod_id}.shadow.net.iharder"
    relocate 'com.sedmelluq.lava', "${project.group}.${mod_id}.shadow.com.sedmelluq.lava"
    relocate 'org.apache.http', "${project.group}.${mod_id}.shadow.org.apache.http"
    relocate('org.apache.commons', "${project.group}.${mod_id}.shadow.org.apache.commons") {
        include 'org.apache.commons.logging.**'
        include 'org.apache.commons.io.**'
        include 'org.apache.commons.codec.**'
    }
    relocate 'com.github', "${project.group}.${mod_id}.shadow.com.github"
    relocate 'com.alibaba', "${project.group}.${mod_id}.shadow.com.alibaba"
    relocate 'com.mpatric', "${project.group}.${mod_id}.shadow.com.mpatric"
    relocate('com.sedmelluq.discord.lavaplayer', "${project.group}.${mod_id}.shadow.com.sedmelluq.discord.lavaplayer") {
        exclude 'com.sedmelluq.discord.lavaplayer.natives.**'
    }

    mergeServiceFiles {
        relocate 'javax.ws.rs.ext', "${project.group}.${mod_id}.shadow.javax.ws.rs.ext"
        relocate 'org.glassfish.jersey.internal.spi', "${project.group}.${mod_id}.shadow.org.glassfish.jersey.internal.spi"
    }

    relocate 'ibxm', "${project.group}.${mod_id}.shadow.ibxm"
    relocate 'net.sourceforge.jaad', "${project.group}.${mod_id}.shadow.net.sourceforge.jaad"
    relocate 'org.mozilla.javascript', "${project.group}.${mod_id}.shadow.org.mozilla.javascript"
    relocate 'org.mozilla.classfile', "${project.group}.${mod_id}.shadow.org.mozilla.classfile"
    relocate 'dev.lavalink.youtube', "${project.group}.${mod_id}.shadow.dev.lavalink.youtube"
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            setConfigName("fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
        data {
            inherit client
            setConfigName("fabric Data")
            ideConfigGenerated(true)
            runDir("build/datagen")

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":common").file("src/generated/resources")}"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
        }
    }
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn('build')
    description = 'Publishes the Fabric build to CurseForge.'
    group = 'publishing'

    apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

    def mainFile = upload(curseforge_project_id, file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"))
    mainFile.changelog = rootProject.file('CHANGELOG.md').text
    mainFile.addRequirement("fabric-api")
    mainFile.addRequirement("balm-fabric")
    project.minecraft_versions.split(',').toList().each { mainFile.addGameVersion(it) }
    mainFile.releaseType = "release"
}

modrinth {
    token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
    projectId = project.modrinth_project_id
    versionType = project.modrinth_release_type
    versionNumber = project.version + "+fabric-" + project.minecraft_version
    uploadFile = remapJar
    changelog = rootProject.file("CHANGELOG.md").text
    gameVersions = project.minecraft_versions.split(',').toList()
    syncBodyFrom = rootProject.file("modpage.md").text
    loaders = ['fabric']
    dependencies {
        required.project "fabric-api"
        required.project "balm"
    }
}
