dependencies {
    modImplementation("net.blay09.mods:balm-fabric:${balm_version}") {
        exclude(group: "net.blay09.mods", module: "shared-bridge")
        changing = balm_version.contains("SNAPSHOT")
    }
    modImplementation("net.blay09.mods:kuma-api-fabric:${kuma_version}")
    modCompileOnly "com.terraformersmc:modmenu:$modmenu_version"
    shadowIn("dev.arbjerg:lavaplayer:2.2.6") {
        exclude(group: "dev.arbjerg", module: "lavaplayer-natives")
    }
    shadowIn("dev.lavalink.youtube:v2:1.17.0")
}
