# Mod Properties
version = 1.5.0
mod_id = mediaradio
mod_name = Media Radio
group = net.jacobwasbeast
description=A mod which adds a media radio with handheld and placeable playback, playlists, and synchronized shared metadata.
homepage=https://github.com/jacobwasbeast/MediaRadio-Minecraft
sources=https://github.com/jacobwasbeast/MediaRadio-Minecraft
issues=https://github.com/jacobwasbeast/MediaRadio-Minecraft/issues
discord=https://discord.gg/
license=MIT
mod_author = Jacobwasbeast
credits = Jacobwasbeast

# Publishing Properties
curseforge_release_type = release
curseforge_project_id = 0
modrinth_release_type = release
modrinth_project_id = 0

# Minecraft Properties
minecraft_version = 1.21.1
minecraft_versions = 1.21,1.21.1
minecraft_version_range = [1.21,1.22)
java_version = 21

# Parchment
parchment_minecraft = 1.21.1
parchment_version = 2024.11.17

# Balm
balm_version = 21.0.46+1.21.1
balm_version_range = [21.0,)

# NeoForge Properties
neoforge_version = 21.1.209
neoforge_version_range = [21.1,)
neoforge_loader_version_range = [4,)

# Fabric Properties
fabric_version = 0.115.1+1.21.1
fabric_loader_version = 0.16.14

# Dependencies
mixin_version=0.8.7
modmenu_version=11.0.3
kuma_version = [21.0,21.2)
create_neoforge_version = 6.0.4-49+mc1.21.1
create_fabric_version = 6.0.4-49+mc1.21.1

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
