repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup 'curse.maven'
        }
    }

    maven {
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
            includeGroup "dev.architectury"
        }
    }

    maven {
        url = "https://maven.blamejared.com"
        content {
            includeGroup "mezz.jei"
        }
    }

    maven {
        url = "https://maven.bai.lol"
        content {
            includeGroup "mcp.mobius.waila"
            includeGroup "lol.bai"
        }
    }

    maven {
        url = "https://maven.terraformersmc.com/releases"
        content {
            includeGroup "com.terraformersmc"
            includeGroup "dev.emi"
        }
    }

    maven {
        url = "https://jm.gserv.me/repository/maven-public/"
        content {
            includeGroup "info.journeymap"
            includeGroup "mysticdrew"
        }
    }

    maven {
        url = 'https://jitpack.io'
        content {
            includeGroup "com.github.BlueMap-Minecraft"
            includeGroup "com.github.mattidragon"
        }
    }

    maven {
        url = "https://repo.mikeprimm.com/"
        content {
            includeGroup "us.dynmap"
        }
    }
	
	maven {
        url "https://maven.siphalor.de/"
        content {
            includeGroup "de.siphalor"
        }
    }

    maven {
        url = "https://dl.cloudsmith.io/public/novamachina-mods/release/maven/"
        content {
            includeGroup "novamachina.novacore"
            includeGroup "novamachina.exnihilosequentia"
        }
    }

    maven {
        url = "https://m2.dv8tion.net/releases"
        content {
            includeGroup "dev.arbjerg"
        }
    }

    maven {
        url = "https://maven.lavalink.dev/releases"
        content {
            includeGroup "dev.lavalink.youtube"
            includeGroup "dev.lavalink.youtube.plugin"
        }
    }
	
    exclusiveContent {
        forRepository {
            maven {
                name = 'Minecraft'
                url = 'https://libraries.minecraft.net/'
            }
        }
        filter { includeGroupAndSubgroups("com.mojang") }
    }
}
