plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'net.darkhax.curseforgegradle'
    id "com.modrinth.minotaur"
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

configurations {
    shadowIn
    implementation.extendsFrom shadowIn
    additionalRuntimeClasspath.extendsFrom shadowIn
}

dependencies {
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
}

jar {
    dependsOn(tasks.shadowJar)
    from {
        zipTree(tasks.shadowJar.archiveFile.get().asFile)
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

tasks.register('noShadowJar', Jar) {
    archiveClassifier.set("no-shadow")
    from(sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

build.dependsOn(tasks.named('noShadowJar'))

shadowJar {
    archiveClassifier.set("shadow")
    configurations = [project.configurations.shadowIn]

    relocate 'org.json', "${project.group}.${mod_id}.shadow.org.json"
    relocate 'org.slf4j', "${project.group}.${mod_id}.shadow.org.slf4j"
    relocate 'certificates', "${project.group}.${mod_id}.shadow.certificates"
    relocate 'com.fasterxml', "${project.group}.${mod_id}.shadow.com.fasterxml"
    relocate 'org.jsoup', "${project.group}.${mod_id}.shadow.org.jsoup"
    relocate 'mozilla', "${project.group}.${mod_id}.shadow.mozilla"
    relocate 'net.iharder', "${project.group}.${mod_id}.shadow.net.iharder"
    relocate 'org.apache.http', "${project.group}.${mod_id}.shadow.org.apache.http"
    relocate('org.apache.commons', "${project.group}.${mod_id}.shadow.org.apache.commons") {
        include 'org.apache.commons.logging.**'
        include 'org.apache.commons.io.**'
        include 'org.apache.commons.codec.**'
    }
    relocate 'com.github', "${project.group}.${mod_id}.shadow.com.github"
    relocate 'com.alibaba', "${project.group}.${mod_id}.shadow.com.alibaba"
    relocate 'com.mpatric', "${project.group}.${mod_id}.shadow.com.mpatric"

    mergeServiceFiles {
        relocate 'javax.ws.rs.ext', "${project.group}.${mod_id}.shadow.javax.ws.rs.ext"
        relocate 'org.glassfish.jersey.internal.spi', "${project.group}.${mod_id}.shadow.org.glassfish.jersey.internal.spi"
    }

    relocate 'ibxm', "${project.group}.${mod_id}.shadow.ibxm"
    relocate 'net.sourceforge.jaad', "${project.group}.${mod_id}.shadow.net.sourceforge.jaad"
    relocate 'org.mozilla.javascript', "${project.group}.${mod_id}.shadow.org.mozilla.javascript"
    relocate 'org.mozilla.classfile', "${project.group}.${mod_id}.shadow.org.mozilla.classfile"
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

task curseforge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    dependsOn('build')
    description = 'Publishes the Forge build to CurseForge.'
    group = 'publishing'

    apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

    def projectId = findProperty("curseforge_project_id")
    onlyIf {
        projectId != null
    }
    if (projectId) {
        def mainFile = upload(findProperty("curseforge_project_id"), file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"))
        mainFile.changelog = rootProject.file('CHANGELOG.md').text
        mainFile.addRequirement("balm")
        project.minecraft_versions.split(',').toList().each { mainFile.addGameVersion(it) }
        mainFile.releaseType = "release"
    }
}

modrinth {
    token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
    projectId = findProperty("modrinth_project_id")
    versionType = "release"
    versionNumber = project.version + "+forge-" + project.minecraft_version
    uploadFile = jar
    changelog = rootProject.file("CHANGELOG.md").text
    gameVersions = project.minecraft_versions.split(',').toList()
    syncBodyFrom = rootProject.file("modpage.md").text
    loaders = ['forge']
    dependencies {
        required.project "balm"
    }
}
